### ISSUE TITLE
no 'rtsol' anymore for OpenBSD -current

### ISSUE THREAD

**Issue by buzzdeee** [xaque208/puppet-bsd#36]
Hi,

just figured, that the 'rtsol' paramter on OpenBSD -current is 'gone'.
Now it's 'inet6 autoconf' to enable the same functionality.

Sebastian

**Comment by xaque208** [comment]
Thank you.

**Comment by xaque208** [comment]
Does that mean 5.7 will ship with this change?

**Comment by buzzdeee** [comment]
Yes, the current 5.7 beta doesn't have the rtsol daemon anymore. This functionality now moved to the kernel.

Have a patch already prepared, when the other one is merged, I go create a new branch with that one.

**Comment by xaque208** [comment]
5.7 has been released.  I'm slow to upgrade.  Hopefully in the next week or so.

**Comment by buzzdeee** [comment]
I also hope, to find a bit time next week. The question basically is:
do you want to stay backward compatible or not? 
I guess yes, ;)

So with backward compatibiliy, should the user disinguish between pre and after 5.6, and give the right options, i.e. rtsol for 5.6, and 'inet autoconf' for 5.7 and onward.
OR should the module smart enough, if either of both is given, based on the OS version, it will figure it out automatically?

For the sake of easier implementation I'd go for the first one, so the admin has to specify the right parameters for the OS version he is using/managing.

What do you think?

**Comment by xaque208** [comment]
I'm thinking about from the perspective where a user doesn't read the release notes.  The module poses the question "would you like to accept router advertisements", and I'd think it would make for a better user experience to just be able to answer "yes" without having to understand what the underlying options are.  I only really care about being backwards compatible for a version or so.  Given that OpenBSD really only seems to support the latest version, lets just move with that, but assist in the transition.

Code wins arguments though, so if you get at thing working, then lets review it.  We could go with the first option you mentioned, but lets document it somewhere, so people coming in new or upgrading know what they are getting into.

**Comment by xaque208** [comment]
@buzzdeee Did we get this resolved?  Now that 5.8 is on its way, I care even less about old versions.

**Comment by buzzdeee** [comment]
@xaque208 jepp, that was PR #57 , and this was forgot to be closed.
