### ISSUE TITLE
wifi interfaces with two static IPs don't work

### ISSUE THREAD

**Issue by buzzdeee** [xaque208/puppet-bsd#38]
I'm running dual-stack @home, so I have IPv4 and IPv6 to configure on my AP. With this, I specify two static IPs:

I have this in Hiera defined:
bsd::network::interface::wifi:
  "%{hiera('node::odo::ds9::wifi_if_name')}":
    network_name: "%{hiera('network::wifi::network_name')}"
    address:
      - "%{hiera('node::odo::ds9::wifi_if_inet')}%{hiera('network::wifi::inet_cidr_netmask')}"
      - "%{hiera('node::odo::ds9::wifi_if_inet6')}/%{hiera('network::wifi::inet6_prefix')}"
    description: 'Access Point'
    options:
      - 'chan 1'
      - 'media OFDM54'
      - 'mode 11g'
      - 'mediaopt hostap'

which produces this result when run:

inet 10.23.4.56 255.255.0.0 NONE inet6 2001:471:4336:ff::1 64 nwid brb.freifunk.net chan 1 media OFDM54 mode 11g mediaopt hostap description "Access Point"
up

which ends up in:

sh /etc/netstart ral0                                          
ifconfig: inet6: bad value

The module should be better splitting up the lines like:
inet 10.23.4.56 255.255.0.0 NONE 
inet6 2001:471:4336:ff::1 64 
nwid brb.freifunk.net chan 1 media OFDM54 mode 11g mediaopt hostap description "Access Point"
up

**Comment by xaque208** [comment]
I'll wait for https://github.com/xaque208/puppet-bsd/pull/34 to get merged, and then I'll write a test for this.

**Comment by xaque208** [comment]
I believe https://github.com/xaque208/puppet-bsd/pull/49 will fix the issue.  Are you able to test out that branch before merge?

**Comment by buzzdeee** [comment]
tested issue38 branch wihtout messing up, and seems to work as advertised.

great, thanks.
