### ISSUE TITLE
order of interface handling in the catalog

### ISSUE THREAD

**Issue by buzzdeee** [xaque208/puppet-bsd#77]
On initial provision, there is no order guaranteed for interface creation.

i.e. you have physical interfaces, trunks on top, vlans on top of trunks, and maybe carp interfaces on the vlan interfaces, etc.
When puppet runs, it may create and start carp interfaces before the vlan interfaces are configured, and so on.

For the interface types in network/interface/*.pp, they all have parameters specifying the parents, i.e. trunk.pp has the 'interface' parameter, vlan.pp and carp.pp have the 'device' parameter.

How about, adding a parameter to bsd::network::interface called parent (should be an array), defaulting to 'undef'.
When configuring a trunk, vlan or carp interface, the given interface or respective device parameters are handed over to the 'parent' parameter of bsd::network::interface when it is called.

Further down the road, add a 'parent' parameter to bsd_interface native type, and hand over the parents if given. Then in bsd_interface, when ensure =  'up' or 'present', there could be an 
autorequire to the parent interface(s)

Do you think that sounds sane and would be feasible?
Other ideas? I'd like to look into that to get something along the lines working.

cheers,
Sebastian

**Comment by xaque208** [comment]
Yes, sounds sane, I like it.  The manifest params as you describe for network/interface/*.pp would be a cheap way to get the require working.  I can look at expanding the native type to support this kind of thing.  `ifconfig -C` on a BSD system will list the interfaces that can be cloned, so it should be easy enough to understand what scope we're dealing with.

The idea of a parent param makes some sense.  Are there cases where a physical interface would have a parent?  If the answer there is no, then we might have a clear path forward.  I'll do a bit of reading in the meantime.

**Comment by buzzdeee** [comment]
I think physical interface either exists, or doesn't exist. I'm not aware of any that could require a parent. The only 'odd' physical interfaces might be hot pluggable, that don't exists all the time, i.e. USB and PCMCIA network or wifi cards, but even those don't have a parent interface.

with regard to ifconfig -C, there are at least a few clonable interfaces, that as far as I know, don't have parent interfaces, i.e. mpe, mpw, or vether at least, maybe more.

On the other hand, some clonable interfaces that can be handled by bsd::network::interface, i.e. pfsync0 have a parent interface. Maybe it might make sense to create a class bsd::network::interface::pfsync? But that definitive for later ;)

Anyways, will first concentrate on the other issue with the values parameter to the other clonable interfaces.

**Comment by xaque208** [comment]
Handled in https://github.com/xaque208/puppet-bsd/pull/79
