### ISSUE TITLE
Ability to manage /etc/login.conf 

### ISSUE THREAD

**Issue by djmentos** [xaque208/puppet-bsd#94]
Hello,

is there any possibility to add to module functions for managing /etc/login.conf entries?

**Comment by xaque208** [comment]
I'd love it.  I think the right way to approach this is to write an augeas lense for termcap generally, and I've just not done it.

**Comment by xaque208** [comment]
This was recently added over at https://github.com/xaque208/puppet-freebsd/blob/master/manifests/login.pp -- maybe that helps.
